# Start from the ubuntu image
FROM ubuntu
# Copy all files from the current linux diretory to the Docker root directory
COPY . .
# Remove previous Go installation, then install gcc, wget and Go 1.16.3
RUN apt-get update && apt-get install -y wget gcc && rm -rf /usr/local/go && \
wget -c https://golang.org/dl/go1.16.3.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
# Add /usr/local/go/bin to the PATH environment variable
ENV PATH /usr/local/go/bin:$PATH
# Run go build. It will generate a binary named server
RUN go build
# Run tests with go test ./...
RUN go test
# Assign CMD in docker run to ./server
CMD ./server
# Expose port 8080
EXPOSE 8080
