services:
    backend:
        container_name: backend
        build: ./example-backend
        ports:
            - 8080:8080
    frontend:
        container_name: frontend
        build: ./example-frontend
        ports:
            - 5000:5000
